version: "3"

tasks:
  install:
    desc: Install dependencies
    cmd: pip install -r requirements.txt

  freeze:
    desc: Freeze the currently installed packages to requirements.txt
    cmd: pip freeze > requirements.txt
